### ISSUE TITLE
MMAction Roadmap

### ISSUE THREAD

**Issue by yjxiong** [open-mmlab/mmaction#1]
## Tasks
- [x] Video classificaiton
  * [x] 2D CNN (RGB, Two-stream CNN) 
  * [x] 3D CNN (I3D)
  * [x] TSN sampling
- [x] Temporal Action Detection 
  * [x] SSN
  * [ ] TAG proposal (v0.2)
  * [ ] BSN proposal (v0.2)
- [x] Spatial Temporal Action Detection (bounding box only)
  * [x] Fast R-CNN + I3D
- [ ] Generic Data Interfaces (v0.1.1)

## Demos (v0.1.1)
  * [ ] Video classification
  * [ ] Temporal action detection
  * [ ] Spatial temporal detection (bounding box only)

## New Operators
  * [x] Trajectory Convolution
  * [ ] 2D Correlection (v0.1.1)
  * [ ] 3D ROIPool (v0.2)

## Dataset
  * [x] UCF101
  * [x] Kinetics-400
  * [ ] SomethingSomething-V1
  * [x] THUMOS14
  * [x] AVA
  * [ ] ActivityNet
  * [x] Custom Dataset
  * [ ] Charades (v0.2)
  * [ ] Epic-Kitchen (v0.2)

## Documentation
 - [x] README
 - [x] Dataset Preparation
 - [x] Getting started guide
 - [ ] Extension guide
 - [x] Model zoo
 - [x] Contributing
 - [x] License

## Model Zoo
- [x] Model files
- [ ] Download links
  * [x] AWS S3
  * [ ] AliCloud

**Comment by zhangluustb** [comment]
If only you made a performance dashboard.
